/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#aec6ff",
        "surface-bright": "#f7f9fb",
        "primary-fixed-dim": "#aec6ff",
        "surface-container-high": "#e6e8ea",
        "primary": "#0058bf",
        "tertiary-fixed-dim": "#bac8d3",
        "on-surface-variant": "#414754",
        "surface-dim": "#d8dadc",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fcfcff",
        "inverse-surface": "#2d3133",
        "tertiary-fixed": "#d6e4ef",
        "secondary-fixed": "#6bfe9c",
        "surface-tint": "#005ac3",
        "secondary-container": "#6bfe9c",
        "on-tertiary-fixed": "#101d25",
        "on-secondary-fixed-variant": "#005228",
        "on-error-container": "#93000a",
        "tertiary": "#505e67",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#00743a",
        "primary-fixed": "#d8e2ff",
        "on-primary-container": "#fefcff",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "outline": "#727786",
        "on-secondary-fixed": "#00210c",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-container": "#697680",
        "on-primary": "#ffffff",
        "outline-variant": "#c1c6d7",
        "on-primary-fixed": "#001a42",
        "primary-container": "#006fee",
        "on-tertiary-fixed-variant": "#3b4851",
        "on-primary-fixed-variant": "#004396",
        "inverse-on-surface": "#eff1f3",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed-dim": "#4ae183",
        "secondary": "#006d37",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
