/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-secondary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "on-secondary-fixed": "#00210c",
                "on-secondary-container": "#00743a",
                "on-tertiary-fixed-variant": "#3b4851",
                "primary-container": "#006fee",
                "tertiary-fixed": "#d6e4ef",
                "on-error-container": "#93000a",
                "tertiary": "#505e67",
                "surface-dim": "#d8dadc",
                "on-primary-fixed": "#001a42",
                "error-container": "#ffdad6",
                "surface-tint": "#005ac3",
                "on-tertiary-container": "#fcfcff",
                "on-secondary-fixed-variant": "#005228",
                "inverse-primary": "#aec6ff",
                "error": "#ba1a1a",
                "secondary-fixed": "#6bfe9c",
                "surface-container": "#eceef0",
                "surface": "#f7f9fb",
                "surface-variant": "#e0e3e5",
                "outline": "#727786",
                "inverse-on-surface": "#eff1f3",
                "on-primary": "#ffffff",
                "surface-container-high": "#e6e8ea",
                "surface-bright": "#f7f9fb",
                "surface-container-low": "#f2f4f6",
                "surface-container-highest": "#e0e3e5",
                "secondary": "#006d37",
                "on-error": "#ffffff",
                "on-primary-fixed-variant": "#004396",
                "inverse-surface": "#2d3133",
                "on-surface": "#191c1e",
                "secondary-container": "#6bfe9c",
                "on-surface-variant": "#414754",
                "background": "#f7f9fb",
                "on-background": "#191c1e",
                "primary-fixed": "#d8e2ff",
                "primary-fixed-dim": "#aec6ff",
                "on-tertiary-fixed": "#101d25",
                "primary": "#0058bf",
                "tertiary-container": "#697680",
                "on-primary-container": "#fefcff",
                "secondary-fixed-dim": "#4ae183",
                "outline-variant": "#c1c6d7",
                "tertiary-fixed-dim": "#bac8d3",
                "on-tertiary": "#ffffff"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Plus Jakarta Sans", "sans-serif"],
                "label": ["Plus Jakarta Sans", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
        },
    },
    plugins: [],
}
